// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkljsuptmhztxjpuhdhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrbGpzdXB0bWh6dHhqcHVoZGhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzODcxODEsImV4cCI6MjA4NTk2MzE4MX0.uybJlXeBcTz2y8BDznNloqLn7UTeM9rSOMMbHtg2yM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});